name: SailfishOS build

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

env:
  RELEASE: 5.0.0.43

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    strategy:
      matrix:
        include:
          - arch: armv7hl
            target: armv7-unknown-linux-gnueabihf
          - arch: aarch64
            target: aarch64-unknown-linux-gnu
          - arch: i486
            target: i686-unknown-linux-gnu

    steps:
    - uses: actions/checkout@v5
      with:
        submodules: recursive

    - name: prepare
      run: mkdir RPMS

    - name: Build ${{ matrix.arch }}
      run: docker run --rm --privileged -v $PWD:/workspace registry.gitlab.com/whisperfish/sailo-rs/rust-${{ matrix.arch }}-$RELEASE /bin/bash -c "
            mkdir -p build ;
            cd build ;
            cp -r /workspace/* . ;
            export OPENSSL_DIR=/usr ;
            sb2 -t SailfishOS-$RELEASE-${{ matrix.arch }} -m sdk-build cargo build --jobs 1 --release --target ${{ matrix.target }} --target-dir rust/target --manifest-path rust/Cargo.toml --locked ;
            mb2 -t SailfishOS-$RELEASE-${{ matrix.arch }} build ;
            sudo cp -r RPMS/*.rpm /workspace/RPMS"

    - name: Upload build result
      uses: actions/upload-artifact@v5
      with:
        name: rpms-${{ matrix.arch }}
        path: RPMS
